feat: Add AI Code Reviewer

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,22 +1,11 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/reference/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
 jobs:
   lint:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
     docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/node
       - image: cimg/node:24.12.0
 
-    # Add steps to the job
-    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
     steps:
-      # Checkout the code as the first step.
       - checkout
       - run:
           name: "Install dependencies"
@@ -25,10 +14,43 @@ jobs:
           name: "Run ESLint"
           command: "pnpm lint"
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
+  code-review:
+    docker:
+      - image: cimg/python:3.11
+
+    steps:
+      - checkout
+      - run:
+          name: Verify required environment variables
+          command: |
+            if [ -z "$GITHUB_TOKEN" ] || \
+               [ -z "$CLAUDE_MODEL" ] || \
+               [ -z "$ANTHROPIC_API_KEY" ] || \
+               [ -z "$CIRCLE_PULL_REQUEST" ] || \
+               [ -z "$CIRCLE_PROJECT_USERNAME" ] || \
+               [ -z "$CIRCLE_PROJECT_REPONAME" ]; then
+              echo "Required environment variables not set"
+              exit 1
+            fi
+      - run:
+          name: Install dependencies
+          command: |
+            pip install -r scripts/requirements.txt
+      
+      - run:
+          name: Run Claude Code Review
+          command: |
+            python scripts/code_reviewer.py
+
+
 workflows:
-  lint-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  pr-review:
     jobs:
       - lint
+      - code-review:
+          requires:
+            - lint
+          filters:
+            branches:
+              ignore:
+                - main
